[project]
name = 'hiro-hacks'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.core]
path = 'contracts/core.clar'
clarity_version = 2
epoch = 2.4

[contracts.ede005-dev-fund]
path = 'contracts/ede005-dev-fund.clar'
clarity_version = 2
epoch = 2.4

[contracts.edp000-bootstrap]
path = 'contracts/edp000-bootstrap.clar'
clarity_version = 2
epoch = 2.4

[contracts.edp001-dev-fund]
path = 'contracts/edp001-dev-fund.clar'
clarity_version = 2
epoch = 2.4

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 2
epoch = 2.4

[contracts.membership-token]
path = 'contracts/membership-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
